region                      = "ap-southeast-1"
vpc_name                    = "komodo_islands"
vpc_cidr                    = "10.2.0.0/16"
eks_cluster_name            = "komodo_cluster"
cidr_block_igw              = "0.0.0.0/0"
node_group_name             = "eks_ng"
ng_instance_types           = [ "t2.small" ]
disk_size                   = 10
desired_nodes               = 2
max_nodes                   = 2
min_nodes                   = 1
fargate_profile_name        = "eks_fargate"
kubernetes_namespace        = "komodo-nest"
deployment_name             = "komodo"
deployment_replicas         = 3
domain_name                 = "syme.fun"
grafana_password            = "admin"
app_labels = { 
    "app" = "komodo"
    "tier" = "backend"
}