# This is a basic workflow to help you get started with Actions

name: CI-CD
env:
  NAMESPACE: komodo-nest
  DEPLOYMENT: komodo-datasaur
  REGION: ap-southeast-1
  CLUSTER_NAME: komodo_cluster-datasaur
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'datasaur-symefa/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.3.0
        with:
          file: datasaur-symefa/Dockerfile
          context: datasaur-symefa/
          push: true
          tags: symefa/datasaur-symefa:latest
      - 
        name: Deploy
        uses: cancue/eks-action@v0.0.3
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $REGION
          cluster_name: $CLUSTER_NAME
        with:
          args: |
            kubectl rollout restart deployment/$DEPLOYMENT -n $NAMESPACE && kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE